"""rename department

Revision ID: a5932fcae360
Revises: dbcb33f503ad
Create Date: 2024-01-18 12:41:14.918601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a5932fcae360"
down_revision = "dbcb33f503ad"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("department", "departments")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("departments", "department")
    # ### end Alembic commands ###
